version: '3.8'
name: canyon
services:
  canyon:
    image: johnnymcneil/enviro-node:latest
    tty: true
    stdin_open: true
    hostname: canyon
    networks:
      environet:
        aliases:
          - canyon
    volumes:
      - canyon-workspace:/workspace

networks:
  environet:

volumes:
  canyon-workspace:
    external: true