version: '3.8'
name: canyon
services:
  canyon:
    image: johnnymcneil/enviro-node:latest
    hostname: canyon
    tty: true
    stdin_open: true
    volumes:
      - canyon-workspace:/workspace

volumes:
  canyon-workspace:
    external: true