version: '3.8'
name: canyon-compose
services:
  canyon:
    image: johnnymcneil/enviro-node:latest
    container_name: canyon
    hostname: canyon
    ports:
      - "3000:3000"
    volumes:
      - canyon-workspace:/workspace

volumes:
  canyon-workspace: